export const PROPERTY_TYPES = {
  HOUSE: "HOUSE",
  APARTMENT: "APARTMENT",
  CONDO: "CONDO",
  VILLA: "VILLA",
  TOWNHOUSE: "TOWNHOUSE",
  LAND: "LAND",
  COMMERCIAL: "COMMERCIAL",
  OTHER: "OTHER",
};

export const PropertyTypeLabels = {
  [PROPERTY_TYPES.HOUSE]: "HOUSE",
  [PROPERTY_TYPES.APARTMENT]: "APARTMENT",
  [PROPERTY_TYPES.CONDO]: "CONDO",
  [PROPERTY_TYPES.TOWNHOUSE]: "TOWNHOUSE",
  [PROPERTY_TYPES.VILLA]: "VILLA",
  [PROPERTY_TYPES.LAND]: "LAND",
  [PROPERTY_TYPES.COMMERCIAL]: "COMMERCIAL",
  [PROPERTY_TYPES.OTHER]: "OTHER",
};

export const PROPERTY_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  PENDING: "PENDING",
  SOLD: "SOLD",
  RENTED: "RENTED",
};
